# Generated by Django 5.2.4 on 2025-07-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_counsellor'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='username',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
