# Generated by Django 5.2.4 on 2025-08-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
